version: '3.8'  # Specify the version of Docker Compose

services:
  client:
    container_name: client
    restart: always
    build: ./client
    ports: 
      - "3000:3000"
    links:
     - app
  app:
    container_name: app  # Name of the container
    restart: always  # Always restart the container if it stops
    build: ./api  # Build the Docker image from the Dockerfile in the api directory
    ports:
      - "4000:4000"  # Map port 4000 on the host to port 4000 on the container
    depends_on:
       - mongo  # Link the app service to the mongo service

  mongo:
    container_name: mongo  # Name of the container
    image: mongo  # Use the official MongoDB image from Docker Hub
    restart: always
    expose:
      - "27017"
    volumes:
      - ./data:/data/db  # Mount the host directory ./data to /data/db in the container
    ports:
      - "27017:27017"  # Map port 27017 on the host to port 27017 on the container